apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-role-binding
  namespace: game
subjects:
- kind: ServiceAccount
  name: game-service-account
  namespace: game
roleRef:
  kind: Role
  name: game-role
  apiGroup: rbac.authorization.k8s.io

