apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: game
  name: game-role
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: []

